name: Marine Self-Powered System Lab
description: Ocean blue energy and new ways of self-powered systems
url: https://mspslab.org
testurl: https://practical-euclid-f7ff6c.netlify.app
markdown: redcarpet
permalink: /:categories/:title/
future: true


redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

exclude:
  - "*.class"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.nb"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.branches"
  - "*.csv"
  - "*.fasta"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.newick"
  - "*.nex"
  - "*.tsv"
  - "*.tips"
  - "*.trees"
  - "*.txt"
  - "*.zip"
  - "*.gz"
  - "*.tiff"
  - "Gemfile"
  - "Gemfile.lock"

plugins:
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-katex

sitemap-force-include:
   - "/pdf/papers/*.pdf"
