backend:
    name: github
    repo: MSPSLab/lab_website 
    branch: main
media_folder: 'images/team'
collections:
  - name: 'Blog'
    label: 'Blog'
    label_singular: "Blog" 
    folder: 'blog/_posts/'
    sort: "date:desc"
    create: true
    slug: "{{date}}-{{slug}}"
    fields:
      - {label: "样式", name: "layout", widget: "hidden", default: "post"}
      - {label: "标题", name: "title", widget: "string", tagname: "h1"}
      - {label: "作者（如：Hengyi Yang）", name: "author", widget: "string", required: false}
      - {label: "链接作者(对应为：Hengyi-Yang)", name: "url_author", widget: "string", required: false}
      - {label: "一句话简介", name: "description", widget: "string", tagname: "h2"}
      - {label: "文件名定义时间（用于手动排序）", name: "date", widget: "datetime", format: "YYYY-M-D"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'News'
    label: 'News'
    label_singular: "News" 
    folder: 'news/_posts/'
    sort: "date:desc"
    create: true 
    slug: "{{date}}-{{slug}}"
    fields:
      - {label: "样式", name: "layout", widget: "hidden", default: "post"}
      - {label: "标题", name: "title", widget: "string", tagname: "h1"}
      - {label: "作者（如：Hengyi Yang）", name: "author", widget: "string", required: false}
      - {label: "链接作者(对应为：Hengyi-Yang)", name: "url_author", widget: "string", required: false}
      - {label: "文件名定义时间（用于手动排序）", name: "date", widget: "datetime", format: "YYYY-M-D"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'Journal Paper'
    label: 'Journal Paper'
    label_singular: "Journal Paper" 
    folder: 'papers/_posts/'
    sort: "date:desc"
    create: true 
    slug: "{{date}}-{{slug}}"
    fields:
      - {label: "样式", name: "layout", widget: "hidden", default: "paper"}
      - {label: "标题", name: "title", widget: "string", tagname: "h1"}
      - {label: "论文缩略图", name: "image", widget: "image", allow_multiple: false}
      - {label: "作者（英文逗号分隔）", name: "authors", widget: "string"}
      - {label: "出版年份", name: "year", widget: "string"}
      - {label: "短引用（如：XX. et al. Nano Energy.）", name: "ref", widget: "string"}
      - {label: "期刊&页码（无需年份）", name: "journal", widget: "string"}
      - {label: "PDF链接（使用jsdelivr地址）", name: "pdf", widget: "string"}
      - {label: "DOI号", name: "doi", widget: "string"}  
      - {
          label: "类型",
          name: "type",
          widget: "select",
          options:
            [{ label: "期刊", value: "journal" }],
        }
      - {label: "文件名定义时间（用于手动排序）", name: "date", widget: "datetime", format: "YYYY-M-D"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'Conference Paper'
    label: 'Conference Paper'
    label_singular: "Conference Paper" 
    folder: 'papers/_posts/'
    sort: "date:desc"
    create: true 
    slug: "{{date}}-{{slug}}"
    fields:
      - {label: "样式", name: "layout", widget: "hidden", default: "paper"}
      - {label: "标题", name: "title", widget: "string", tagname: "h1"}
      - {label: "论文缩略图", name: "image", widget: "image", allow_multiple: false}
      - {label: "作者（英文逗号分隔）", name: "authors", widget: "string"}
      - {label: "出版年份", name: "year", widget: "string"}
      - {label: "短引用（如：XX. et al. Nano Energy.）", name: "ref", widget: "string"}
      - {label: "会议&页码（无需年份）", name: "journal", widget: "string"}
      - {label: "PDF链接（使用jsdelivr地址）", name: "pdf", widget: "string"}
      - {label: "DOI号", name: "doi", widget: "string"}  
      - {
          label: "类型",
          name: "type",
          widget: "select",
          options:
            [{ label: "会议", value: "conference" }],
        }
      - {label: "文件名定义时间（用于手动排序）", name: "date", widget: "datetime", format: "YYYY-M-D"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'Patents'
    label: 'Patents'
    label_singular: "Patents" 
    folder: 'papers/_posts/'
    sort: "date:desc"
    create: true 
    slug: "{{date}}-{{slug}}"
    fields:
      - {label: "样式", name: "layout", widget: "hidden", default: "paper"}
      - {label: "标题", name: "title", widget: "string", tagname: "h1"}
      - {label: "论文缩略图", name: "image", widget: "image", allow_multiple: false}
      - {label: "作者（英文逗号分隔）", name: "authors", widget: "string"}
      - {label: "出版年份", name: "year", widget: "string"}
      - {label: "短引用（如：XX. et al. Nano Energy.）", name: "ref", widget: "string"}
      - {label: "会议&页码（无需年份）", name: "journal", widget: "string"}
      - {label: "申请专利号", name: "num", widget: "string"}
      - {label: "分类号（长分类中间用空格分隔）", name: "catenum", widget: "string"}  
      - {label: "主分类号", name: "mainnum", widget: "string"}  
      - {
          label: "类型",
          name: "type",
          widget: "select",
          options:
            [{ label: "专利", value: "patents" }],
        }
      - {label: "文件名定义时间（用于手动排序）", name: "date", widget: "datetime", format: "YYYY-M-D"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'Book'
    label: 'Book'
    label_singular: "Book" 
    folder: 'papers/_posts/'
    sort: "date:desc"
    create: true 
    slug: "{{date}}-{{slug}}"
    fields:
      - {label: "样式", name: "layout", widget: "hidden", default: "paper"}
      - {label: "标题", name: "title", widget: "string", tagname: "h1"}
      - {label: "论文缩略图", name: "image", widget: "image", allow_multiple: false}
      - {label: "作者（英文逗号分隔）", name: "authors", widget: "string"}
      - {label: "出版年份", name: "year", widget: "string"}
      - {label: "短引用（如：XX. et al. Nano Energy.）", name: "ref", widget: "string"}
      - {label: "会议&页码（无需年份）", name: "journal", widget: "string"}
      - {label: "ISBN号码", name: "ISBN", widget: "string"}  
      - {label: "书本销售链接", name: "bookurl", widget: "string"}  
      - {
          label: "类型",
          name: "type",
          widget: "select",
          options:
            [{ label: "书籍", value: "book" }],
        }
      - {label: "文件名定义时间（用于手动排序）", name: "date", widget: "datetime", format: "YYYY-M-D"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'Team'
    label: 'Team'
    label_singular: "Team" 
    folder: 'team/_posts/'
    sort: "date:desc"
    create: true 
    slug: "{{date}}-{{slug}}"
    fields:
      - {label: "样式", name: "layout", widget: "hidden", default: "member"}
      - {label: "姓名（如：Hengyi Yang）", name: "title", widget: "string", tagname: "h1"}
      - {label: "姓氏（用于自动排序，如 Yang）", name: "handle", widget: "string"}
      - {
          label: "职位",
          name: "position",
          widget: "select",
          options:
            [{ label: "教授", value: "Professor" }, { label: "副教授", value: "Associate Professor" }, { label: "讲师", value: "Lecturer" }, { label: "实验师", value: "Experimentalist" }, { label: "博士生", value: "Ph.D. candidate" }, { label: "硕士生", value: "Master degree candidate" }, { label: "本科生", value: "Bachelor degree candidate" }, { label: "往届生", value: "Prior member" }, { label: "访问者", value: "Visiting member" }],
        }
      - {label: "邮箱", name: "email", widget: "string"}
      - {label: "Github", name: "github", widget: "string", required: false}
      - {label: "谷歌Scholar", name: "scholar", widget: "string", required: false}
      - {label: "Orcid", name: "orcid", widget: "string", required: false}
      - {label: "头像（149*149像素）", name: "image", widget: "image", allow_multiple: false}
      - {label: "简历文件", name: "cv", widget: "string", required: false}
      - {label: "文件名定义时间（用于手动排序）", name: "date", widget: "datetime", format: "YYYY-M-D"}
      - {label: "Body", name: "body", widget: "markdown"}  