backend:
    name: github
    repo: MSPSLab/lab_website # Path to your GitHub repository
    branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'post'
    label: 'Posts'
    label_singular: "Post" # Used in the UI, ie.: "New Post"
    folder: '_posts/'
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Blog_Author", name: "author", widget: "string"}
      - {label: "Blog_Url_author", name: "url_author", widget: "string"}
      - {label: "Blog_Description", name: "description", widget: "string", tagname: "h2"}
      - {label: "Paper_image", name: "image", widget: "image", allow_multiple: false}
      - {label: "Paper_Authors", name: "authors", widget: "string"}
      - {label: "Paper_Year", name: "year", widget: "string"}
      - {label: "Paper_Ref", name: "ref", widget: "string"}
      - {label: "Paper_Journal", name: "journal", widget: "string"}
      - {label: "Paper_Pdf", name: "pdf", widget: "string"}
      - {label: "Paper_Doi", name: "doi", widget: "string"}
      - {label: "Paper_Type", name: "type", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: "Body", name: "body", widget: "markdown"}
