name: File Sync

on:
  push:
    branches:
      - master

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: File Sync
        uses: MSPSLab/lab_website
        with:
          REPOSITORIES: |
            yhyates/lab_website_personal@master
          PULL_REQUEST_BRANCH_NAME: main
          FILES: |
            sync/dependabot.yml=.github/dependabot.yml
          TOKEN: ${{ secrets.ACTIONS }}
